vim.opt.number = true -- Exibe números das linhas
vim.opt.relativenumber = false -- Números relativos
vim.opt.expandtab = true -- Converte TAB para espaços
vim.opt.shiftwidth = 2 -- Número de espaços para cada indentação
vim.opt.tabstop = 2 -- Tamanho da tecla TAB
vim.opt.signcolumn = "yes" -- Coluna para diagnósticos
vim.opt.guicursor = "n-v-c:block" -- Cursor em bloco
vim.opt.history = 1000 -- Histórico de comandos
vim.opt.incsearch = true -- Pesquisa incremental
vim.opt.ignorecase = true -- Pesquisa case insensitive
vim.opt.smartcase = true -- Sensível a maiúsculas na pesquisa
vim.opt.errorbells = false -- Desabilita sons
vim.opt.visualbell = false -- Desabilita alertas visuais
vim.opt.showmode = false -- Oculta o modo do editor
vim.opt.syntax = "on" -- Realce de sintaxe
vim.opt.cursorline = true -- Destaque da linha atual
vim.opt.winblend = 10 -- Transparência para janelas flutuantes
vim.opt.timeoutlen = 300 -- Tempo de espera para mapeamentos
vim.opt.linebreak = true -- Quebra de linhas por palavras
vim.opt.colorcolumn = "100" -- Limita largura da tela
vim.opt.lazyredraw = true -- Melhora desempenho ao desativar animações
vim.opt.ruler = true -- Mostra posição do cursor
vim.opt.title = true -- Mostra o título da janela
vim.opt.titlestring = "%F" -- Exibe o caminho completo do arquivo no título
